### ISSUE TITLE
Question - ImageAnnotation on log graph

### ISSUE THREAD

**Issue by Sl1ckR1ck** [ylatuya/oxyplot#5]
So this is not really an issue, but more of a question.

I have an application which is to import an graph image and let the user replicate the graph by specifying points on top of this image.

This works great when i have linear axes. However when using an image with log axes, the image doesn't scale properly when zooming in and out.

I was thinking of implementing my own special annotation where I would specify two corners of the image and enter what should be the coordinate in the real plotmodel system of units.

This way after zooming in/out i would change the dimension of the image to ensure that it continues to display inside the two points i have specified.

However, i was wondering if maybe oxyplot already supported this kind and maybe i missed something?

Thanks

**Comment by ylatuya** [comment]
This repository is a fork of Oxyplot I started to support mono. The original repo is https://github.com/oxyplot/oxyplot
